name: fetch content from Notion & public Moments on Vercel
on:
  workflow_dispatch:
  push:
  schedule:
    - cron:  '0,30 * * * *'

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      NOTION_SECRET: ${{secrets.NOTION_SECRET}}
      NOTION_DATABASE_ID: ${{secrets.NOTION_DATABASE_ID}}
      HUGO_VERSION: 0.85.0
    steps:
      - name: Checkout repo files
        uses: actions/checkout@v4 
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.0'
      - run: pip install notion-client
      - run: git clone --branch master --depth 1 https://github.com/FarseaSH/notion-moments-database-parser.git ./scripts
      - run: python scripts/main.py
      - run: git clone --branch dev --depth 1 https://github.com/FarseaSH/hugo-theme-moments.git ./themes/moments
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'
          extended: true
      - name: Hugo build
        run: hugo
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
          working-directory: ./public

